services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS zeeguu_test;" -uroot
  - mysql -e "grant all on zeeguu_test.* to 'zeeguu_test'@'localhost' identified by 'zeeguu_test';"


language: python
python:
  - "2.7"

install: "python setup.py develop"

script: "./run_tests.sh"
